version: '3.8'

services:
  validator_alpha:
    build: .
    command: python run_node.py --ip=0.0.0.0 --node_port=9010 --api_port=9050 --key_file=./keys/genesis_private_key.txt
    entrypoint: ["/usr/src/node/entrypoint.sh"]
    volumes:
      - .:/usr/src/node
    environment:
      - USE_DOCKER=True
      - DOCKER_NODE_CONTAINER_NAMES=pos-blockchain-validator_alpha-1,pos-blockchain-validator_beta-1,pos-blockchain-validator_gamma-1,pos-blockchain-validator_delta-1
      - DOCKER_NODE_PORTS=9010,9011,9012,9013
    ports:
      - 9010:9010
      - 9050:9050

  validator_beta:
    build: .
    command: python run_node.py --ip=0.0.0.0 --node_port=9011 --api_port=9051 --key_file=./keys/staker_private_key.txt
    entrypoint: ["/usr/src/node/entrypoint.sh"]
    volumes:
      - .:/usr/src/node
    environment:
      - USE_DOCKER=True
      - DOCKER_NODE_CONTAINER_NAMES=pos-blockchain-validator_alpha-1,pos-blockchain-validator_beta-1,pos-blockchain-validator_gamma-1,pos-blockchain-validator_delta-1
      - DOCKER_NODE_PORTS=9010,9011,9012,9013
    ports:
      - 9011:9011
      - 9051:9051
    depends_on:
      - validator_alpha

  validator_gamma:
    build: .
    command: python run_node.py --ip=0.0.0.0 --node_port=9012 --api_port=9052
    entrypoint: ["/usr/src/node/entrypoint.sh"]
    volumes:
      - .:/usr/src/node
    environment:
      - USE_DOCKER=True
      - DOCKER_NODE_CONTAINER_NAMES=pos-blockchain-validator_alpha-1,pos-blockchain-validator_beta-1,pos-blockchain-validator_gamma-1,pos-blockchain-validator_delta-1
      - DOCKER_NODE_PORTS=9010,9011,9012,9013
    ports:
      - 9012:9012
      - 9052:9052
    depends_on:
      - validator_alpha

  validator_delta:
    build: .
    command: python run_node.py --ip=0.0.0.0 --node_port=9013 --api_port=9053
    entrypoint: ["/usr/src/node/entrypoint.sh"]
    volumes:
      - .:/usr/src/node
    environment:
      - USE_DOCKER=True
      - DOCKER_NODE_CONTAINER_NAMES=pos-blockchain-validator_alpha-1,pos-blockchain-validator_beta-1,pos-blockchain-validator_gamma-1,pos-blockchain-validator_delta-1
      - DOCKER_NODE_PORTS=9010,9011,9012,9013
    ports:
      - 9013:9013
      - 9053:9053
    depends_on:
      - validator_alpha
